### ISSUE TITLE
To Do list for v1.0 release

### ISSUE THREAD

**Issue by edwardsmith999** [Crompulence/cpl-library#10]
I have just committed an attempt at number 4

1) Setup documentation for website [ERF]
    a) Scripts for sphinx and code-highlight
    b) Add scripts to git hooks to ensure regenerated when codes changed

2) API clean up html so fits with rest of CPL library [ERF]

3) Travis CI [ERF]
    a) Add examples as final test with 6 perms of f90, cpp and py
    b) Add website sphinx and code highlight autogenerate

4) Documentation for existing routines [ES]
    a) CPL init, CPL setup_CFD, CPL setup md, CPL portions

5) Visual example with plots using python attached to fortran/cpp codes [ES]

6) minimal MD and CFD python example [ES]

7)  New functions
    a) Write and add CPL_read and CPL_write functions with wrappers [ES]
    b) CPL_setup_cpl(Stuff, from, input, file, here) [ERF?]

Think that was everything, let me know if you had anything else

**Comment by edu159** [comment]
That is perfectly fine. As I told you, I will delay 3.a for now since it is not a priority, OK?
Regarding CPL_setup_cpl() I will think about how to do it properly and come back to you.

**Comment by edwardsmith999** [comment]
Sure, I've added the a script which builds and tests all 9 permutations to the example directory which could be simply called as part of tests for now... 

CPL_setup_cpl() will initially need to take ONLY data which is currently obtained as part of the read_input function. In time the general type interface with arbitrary patches is a good idea
