### ISSUE TITLE
Remove nstep, initialstep and dt from setup (and density?)

### ISSUE THREAD

**Issue by edwardsmith999** [Crompulence/cpl-library#11]
I propose these be removed as they are not essential and currently serve as a check only. I will add a routine `CPL_set_times(nsteps, initialstep, dt)` to broadcast and setup the coupled time so the user can do this if they want. Any objections? Means another interface changed but better now than before release...

**Comment by edu159** [comment]
I agree on that. It is something I thought before. Makes more general cpl_setup routines.

Edu

**Comment by edwardsmith999** [comment]
Done, I've updated tests and examples and commented out the website build so we don't get build failure on travis.
