### ISSUE TITLE
Send size checking in CPL_send and CPL_recv operations

### ISSUE THREAD

**Issue by edwardsmith999** [Crompulence/cpl-library#18]
In CPL_send and CPL_recv an array with mismatch in 1st dimension size, this error passes silently. We ideally need some form of initial communication in the first few CPL_send and recv operations to check that this is sending what is expected.

**Comment by edu159** [comment]
I agree this is a good consistency check and I do not see a reason for not having it.

**Comment by edwardsmith999** [comment]
Done since latest commit, decided to create a COMM for all processes in overlapping region and used MPI_allreduce to check average value is the same as each sent value. This will cause problems if the number of sent values changes or different number of values on different processes.
