### ISSUE TITLE
Warning -- different CPL linked into executables

### ISSUE THREAD

**Issue by xcx1212** [Crompulence/cpl-library#24]
Hi. I installed cpl-library, CPL_APP_LAMMPS-DEV and CPL_APP_OPENFOAM-3.0.1, and when I run the example: cpl-library/examples/LAMMPS_OPENFOAM, a warning appears: Warning -- different CPL linked into executables. How can I fix the warning? Please help, thanks.

**Comment by edwardsmith999** [comment]
Sorry for the very slow reply on this. The cplexec has been updated to be better at identifying version of CPL and MPI. THe option is to run cplexec with the permissive flag to disable this check
`cplexec -p`
