### ISSUE TITLE
std __throw_bad_array_new_length compiler error

### ISSUE THREAD

**Issue by edwardsmith999** [Crompulence/cpl-library#26]
When compiling the minimal examples with gcc  on ARCHER2, the following error is raised

```
 cplf90 ./md_recv_cells.f90 -o ./md.exe
/usr/bin/ld: /home/cpl-library/lib/libcpl.so: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
collect2: error: ld returned 1 exit status

```

**Comment by gavinpringle** [comment]
Actually, if one unloads the OF module, which switched many modules including gcc v11 to v10, and then switch gcc v10 back to v11, it works.  This reinforces my idea that the OF module is a little tricky and needs attention.  I took an action at our last meeting to clear up the OF module.  I suggest we stick with gcc v10 for now, nonetheless.
