### ISSUE TITLE
Possible python binding error with version of mpich 3.1 and ifort

### ISSUE THREAD

**Issue by edwardsmith999** [Crompulence/cpl-library#4]
On call to load_library, the following error is reported with mpich version 3.1 compiled with intel fortran 14.0.2:

`PATH/TO/mpich3.1-install/lib/libmpich.so.12: undefined symbol: MPL_large_writev`

where ldd libmpich.so.12 returns:

`linux-vdso.so.1 =>  (0x00007fff5c84a000)
    libmpl.so.1 => /home/es205/installed/mpich3.1-install/lib/libmpl.so.1 (0x00007f10ed4c9000)
    libopa.so.1 => /home/es205/installed/mpich3.1-install/lib/libopa.so.1 (0x00007f10ed2c6000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f10ed092000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f10ece75000)
    libifport.so.5 => /opt/intel/composer_xe_2013_sp1.2.144/compiler/lib/intel64/libifport.so.5 (0x00007f10ecc45000)
    libifcore.so.5 => /opt/intel/composer_xe_2013_sp1.2.144/compiler/lib/intel64/libifcore.so.5 (0x00007f10ec905000)
    libimf.so => /opt/intel/composer_xe_2013_sp1.2.144/compiler/lib/intel64/libimf.so (0x00007f10ec442000)
    libsvml.so => /opt/intel/composer_xe_2013_sp1.2.144/compiler/lib/intel64/libsvml.so (0x00007f10eb846000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f10eb54a000)
    libintlc.so.5 => /opt/intel/composer_xe_2013_sp1.2.144/compiler/lib/intel64/libintlc.so.5 (0x00007f10eb2f4000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f10eaf35000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f10edb50000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f10ead1e000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f10eab1a000)
`

**Comment by edu159** [comment]
I think the problem is the make/intel.inc file. To  successfully load a shared library in python, ctypes requires that all the needed symbols are defined in the library. I had to include LFLAGS = -lgfortran -lmpifort in the make/gcc.inc file to make it work, so you have to do the equivalent on the make/intel.inc with intel's version. I don't have any intel compiler installed on my machine (they are not free right?). Can you this?

**Comment by edwardsmith999** [comment]
Hi Eduardo,

Thanks for the reply, I didn't mean for you to fix this, just put it on 
there as a reminder to me. I was planning to recompile mpi with gcc but 
I'll give adding the linker flags for intel a go. Intel is free for 
students but needs to be installed from source (actually a packaged 
installer) so no way to include with Travis, etc.

Cheers,
Ed
