### ISSUE TITLE
undefined symbol in libcpl.so error with gcc and mpich3.2

### ISSUE THREAD

**Issue by edwardsmith999** [Crompulence/cpl-library#5]
After building a version of mpich3.2 with gcc 5.2.1 ( and gfortran version 4.6.4 I'm not sure if the mismatch between gfortran and gcc is the problem) the following error occurs when attempting to import cpllibrary:

``OSError: PATH/TO/cpl-library/cpl/lib/libcpl.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE``

This may be due to stdlib not included in linking stage?

**Comment by edwardsmith999** [comment]
Okay, recompiled mpich with gcc-5 and gfortran-5 (both gcc 5.2.1 bundle) and still getting the same error... Compiler runs as follows:

``mpif90 -fno-underscoring -O3 -Jinclude -fPIC -c src/core/CPL_module.f90 -o obj/CPL_module.o
mpif90 -fno-underscoring -O3 -Jinclude -fPIC -c src/core/CPL_methods.f90 -o obj/CPL_methods.o
mpif90 -fno-underscoring -O3 -Jinclude -fPIC -c src/bindings/fortran/CPL.f90 -o obj/CPL.o
mpif90 -fno-underscoring -O3 -Jinclude -fPIC -c src/bindings/c/CPLC.f90 -o obj/CPLC.o
mpic++ -std=c++14 -O3 -fPIC -Isrc/bindings/c -c src/bindings/cpp/CPLCPP.cpp -o obj/CPLCPP.o
mpic++ -std=c++14 -O3 -fPIC -Isrc/utils -c src/utils/CPL_ndArray.cpp -o obj/CPL_ndArray.o
mpic++ -std=c++14 -O3 -fPIC -Isrc/utils -c src/utils/CPL_cartCreate.cpp -o obj/CPL_cartCreate.o
mpic++ -std=c++14 -O3 -fPIC -Isrc/utils -c src/utils/CPL_vector3D.cpp -o obj/CPL_vector3D.o
mpic++ -std=c++14 -O3 -fPIC -Isrc/utils -c src/utils/CPL_usherBase.cpp -o obj/CPL_usherBase.o
mpic++ -shared -o lib/libcpl.so obj/CPL_module.o obj/CPL_methods.o obj/CPL.o obj/CPLC.o obj/CPLCPP.o obj/CPL_ndArray.o obj/CPL_cartCreate.o obj/CPL_vector3D.o obj/CPL_usherBase.o -lgfortran -lmpifort``

So linking stage doesn't include stdlib but not sure if this is needed? 
The ``ldd libcpl.so`` gives:

	```linux-vdso.so.1 =>  (0x00007fff3f565000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007fd28dbb6000)
	libmpifort.so.12 => /home/es205/installed/mpich_gcc/mpich-3.2_install/lib/libmpifort.so.12 (0x00007fd28d97e000)
	libmpi.so.12 => /home/es205/installed/mpich_gcc/mpich-3.2_install/lib/libmpi.so.12 (0x00007fd28d4ed000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd28d2d6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd28cf17000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fd28ccd8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd28c9dc000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd28c7d3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd28c5b6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd28e156000)```

**Comment by edu159** [comment]
It seems the ABI changed for g++ so no it is needed this symbol to be defined at loading time. Try adding "-l  libcxxabi" at the end of the linking command.

**Comment by edwardsmith999** [comment]
Thanks Edu, adding ``-lstdc++`` to make/gcc.inc fixed it (I don't have cxxabi as a separate library, must be included in stdlib). Is this a problem we'd expect in general or have I messed up my install (i.e. should I push change to ``gcc.inc`` to repo?).
