### ISSUE TITLE
Folder Clean Up

### ISSUE THREAD

**Issue by edwardsmith999** [Crompulence/cpl-library#8]
I propose we rearrange the folder system as follows

cpl-library
---|---> docs
------|---> sphinx_doc
------|---> cpl-library website
---|---> src
------|---> obj
------|---> include
---|---> lib
---|---> examples
---|---> make
---|---> tests

Where we have
moved cpl/doc_sphinx to doc
moved cpl/src/bindings/python/examples to examples
cpl is renamed to src
demo is renamed to examples

The api reference can then be automatically generated from the latest code (sphinx) while the code examples for the website can be generated with something like highlight (http://www.gnu.org/software/src-highlite/)

What do you think?

**Comment by edu159** [comment]
Yes! I agree that is a good rearrangement. I would just merge docs and
sphinx_doc into a single folder "doc" and rename "tests" to "test" to
follow the common naming convention one usually finds in open-source
projects.

Edu

**Comment by edwardsmith999** [comment]
Looks very good +tests working :)  Should I close this?

**Comment by edu159** [comment]
Yes, I think so. I cut down the examples so CFD send and MD receives as the intention was to be a minimal example. Also I removed the array_stuff module. It can be recovered if needed! What do you think?

**Comment by edwardsmith999** [comment]
No, sounds good, minimal should be as minimal as possible. Are the example permutations part of the tests for the various combinations of language? When these work as part of the testing framework then we are ready to release i think. I'll add topology design tool, a sine send example and md/CFD minimal examples soon.

I see the website is also on the repo, did you clone this and change the pointer on the web server so it's the latest git version? We could set to regenerate docs using a git hook & setup a chron tab on the server to pull every day so we never need to adapt the website on the server directly. Is this sensible?
________________________________
